name: firebase_bloc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  equatable: ^1.0.3
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  json_serializable: ^3.2.5
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  bloc_test: ^3.1.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
